/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  PietrzakVerifier,
  PietrzakVerifierInterface,
} from "../PietrzakVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "base",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "e",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "m",
        type: "bytes",
      },
    ],
    name: "bignum_expmod",
    outputs: [
      {
        internalType: "bytes",
        name: "o",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "x",
        type: "uint256",
      },
    ],
    name: "log2",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_x",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_y",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_u",
        type: "bytes",
      },
    ],
    name: "r_value",
    outputs: [
      {
        internalType: "bytes16",
        name: "result",
        type: "bytes16",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class PietrzakVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): PietrzakVerifierInterface {
    return new utils.Interface(_abi) as PietrzakVerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PietrzakVerifier {
    return new Contract(address, _abi, signerOrProvider) as PietrzakVerifier;
  }
}
