/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "BigNumbers",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BigNumbers__factory>;
    getContractFactory(
      name: "BqETH",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BqETH__factory>;
    getContractFactory(
      name: "PietrzakVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PietrzakVerifier__factory>;

    getContractAt(
      name: "BigNumbers",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BigNumbers>;
    getContractAt(
      name: "BqETH",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.BqETH>;
    getContractAt(
      name: "PietrzakVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PietrzakVerifier>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
