/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PietrzakVerifierInterface extends ethers.utils.Interface {
  functions: {
    "expmod(uint256,uint256,uint256)": FunctionFragment;
    "log2(uint256)": FunctionFragment;
    "r_value(uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "expmod",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "log2", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "r_value",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "expmod", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "log2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "r_value", data: BytesLike): Result;

  events: {};
}

export class PietrzakVerifier extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PietrzakVerifierInterface;

  functions: {
    expmod(
      base: BigNumberish,
      e: BigNumberish,
      m: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { o: BigNumber }>;

    log2(x: BigNumberish, overrides?: CallOverrides): Promise<[number]>;

    r_value(
      _x: BigNumberish,
      _y: BigNumberish,
      _u: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  expmod(
    base: BigNumberish,
    e: BigNumberish,
    m: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  log2(x: BigNumberish, overrides?: CallOverrides): Promise<number>;

  r_value(
    _x: BigNumberish,
    _y: BigNumberish,
    _u: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    expmod(
      base: BigNumberish,
      e: BigNumberish,
      m: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    log2(x: BigNumberish, overrides?: CallOverrides): Promise<number>;

    r_value(
      _x: BigNumberish,
      _y: BigNumberish,
      _u: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    expmod(
      base: BigNumberish,
      e: BigNumberish,
      m: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    log2(x: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    r_value(
      _x: BigNumberish,
      _y: BigNumberish,
      _u: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    expmod(
      base: BigNumberish,
      e: BigNumberish,
      m: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    log2(
      x: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    r_value(
      _x: BigNumberish,
      _y: BigNumberish,
      _u: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
